// Generated by Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
#ifndef INTERCOM_SWIFT_H
#define INTERCOM_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <Intercom/Intercom.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Intercom",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;

SWIFT_CLASS("_TtC8Intercom15ArticleMetaData")
@interface ArticleMetaData : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull searchBrowseSource;)
+ (NSString * _Nonnull)searchBrowseSource SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nullable articleId;
@property (nonatomic, copy) NSString * _Nullable articleSource;
- (nonnull instancetype)initWithId:(NSString * _Nullable)id source:(NSString * _Nullable)source OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;

SWIFT_CLASS("_TtC8Intercom22AvailableTeammatesView")
@interface AvailableTeammatesView : UIStackView
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, CardType, open) {
  CardTypePost = 0,
  CardTypeTicket = 1,
};


SWIFT_PROTOCOL("_TtP8Intercom16CardViewDelegate_")
@protocol CardViewDelegate
- (void)cardButtonTappedFor:(enum CardType)cardType;
@end

@protocol ConversationCardInfoProtocol;
@protocol ConversationCardDelegate;
@class UITraitCollection;

SWIFT_CLASS("_TtC8Intercom16ConversationCard")
@interface ConversationCard : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger maxRecentConversationsCount;)
+ (NSInteger)maxRecentConversationsCount SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat viewPadding;)
+ (CGFloat)viewPadding SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithCardInfo:(id <ConversationCardInfoProtocol> _Nonnull)cardInfo delegate:(id <ConversationCardDelegate> _Nonnull)delegate OBJC_DESIGNATED_INITIALIZER;
- (CGFloat)heightForCardWithWidth:(CGFloat)width SWIFT_WARN_UNUSED_RESULT;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP8Intercom31SeeAllConversationsViewDelegate_")
@protocol SeeAllConversationsViewDelegate
- (void)viewPreviousConversations;
@end


@interface ConversationCard (SWIFT_EXTENSION(Intercom)) <SeeAllConversationsViewDelegate>
- (void)viewPreviousConversations;
@end

@class UIViewController;

SWIFT_PROTOCOL("_TtP8Intercom24ConversationCardDelegate_")
@protocol ConversationCardDelegate
- (void)startNewConversation;
- (void)viewPreviousConversations;
- (void)reloadConversationHistoryCard;
- (void)navigateToViewController:(UIViewController * _Nonnull)viewController;
@end


SWIFT_PROTOCOL("_TtP8Intercom28ConversationCardInfoProtocol_")
@protocol ConversationCardInfoProtocol
@property (nonatomic, readonly) BOOL prominantStyling;
@property (nonatomic, readonly) BOOL accessToTeammateEnabled;
@property (nonatomic, readonly) BOOL hasRecentConversations;
@property (nonatomic, readonly) BOOL hasOtherConversations;
@property (nonatomic, readonly) BOOL startConversationCardDisplayed;
@end

@protocol ICMConfigProtocol;
@protocol ICMDataManagerProtocol;

SWIFT_CLASS("_TtC8Intercom20ConversationCardInfo")
@interface ConversationCardInfo : NSObject <ConversationCardInfoProtocol>
@property (nonatomic, readonly) BOOL prominantStyling;
@property (nonatomic) BOOL startConversationCardDisplayed;
@property (nonatomic, readonly) BOOL accessToTeammateEnabled;
@property (nonatomic, readonly) BOOL hasRecentConversations;
@property (nonatomic, readonly) BOOL hasOtherConversations;
- (nonnull instancetype)initWithProminantStyling:(BOOL)prominantStyling config:(id <ICMConfigProtocol> _Nonnull)config dataManager:(id <ICMDataManagerProtocol> _Nonnull)dataManager OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class ICMRecentConversationsViewController;

SWIFT_CLASS("_TtC8Intercom23ConversationHistoryCard")
@interface ConversationHistoryCard : ConversationCard <ICMRecentConversationsViewControllerDelegate>
@property (nonatomic, strong) ICMRecentConversationsViewController * _Nonnull recentConversationsVC;
- (void)reloadConversationHistoryCard;
- (void)navigateToViewController:(UIViewController * _Nonnull)viewController;
- (nonnull instancetype)initWithCardInfo:(id <ConversationCardInfoProtocol> _Nonnull)cardInfo delegate:(id <ConversationCardDelegate> _Nonnull)delegate OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8Intercom11EmojiButton")
@interface EmojiButton : UIButton
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8Intercom16EmojiImageButton")
@interface EmojiImageButton : UIButton
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class NSError;

SWIFT_CLASS("_TtC8Intercom14ErrorProcessor")
@interface ErrorProcessor : NSObject
+ (NSError * _Nonnull)generateHTTPErrorWithCode:(NSInteger)code message:(NSString * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)generateInvalidUserIdOrEmailError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)generateInvalidUpdateObjectError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)generatePushNotificationsNotEnabledError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)generatePushNotificationNilDeviceTokenError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)generateInvalidIdentityVerificationError SWIFT_WARN_UNUSED_RESULT;
+ (NSError * _Nonnull)generateInvalidDeviceTokenError SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8Intercom26HelpCenterArticle_Internal")
@interface HelpCenterArticle_Internal : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull title;
- (nullable instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id title:(NSString * _Nonnull)title OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSBundle;

SWIFT_CLASS("_TtC8Intercom33HelpCenterContainerViewController")
@interface HelpCenterContainerViewController : UIViewController
- (nonnull instancetype)initWithCollections:(NSArray<NSString *> * _Nonnull)collectionIds;
- (nonnull instancetype)initWithCollection:(NSString * _Nonnull)collectionId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initFromSearchBrowse:(BOOL)fromSearchBrowse;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface HelpCenterContainerViewController (SWIFT_EXTENSION(Intercom)) <ICMErrorViewDelegate>
- (void)didSelectErrorAction;
@end


@class ICMHelpCenterCollection;
@class ICMHelpCenterCollectionContent;
@class ICMHelpCenterArticleSearchResult;

SWIFT_CLASS("_TtC8Intercom21HelpCenterDataService")
@interface HelpCenterDataService : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)fetchCollectionsWithCompletion:(void (^ _Nonnull)(NSArray<ICMHelpCenterCollection *> * _Nullable, NSError * _Nullable))completion;
- (void)fetchCollectionWithCollectionId:(NSString * _Nonnull)collectionId completion:(void (^ _Nonnull)(ICMHelpCenterCollectionContent * _Nullable, NSError * _Nullable))completion;
- (void)searchResultsFor:(NSString * _Nonnull)searchTerm completion:(void (^ _Nonnull)(NSArray<ICMHelpCenterArticleSearchResult *> * _Nullable, NSError * _Nullable))completion;
@end

@class NSNumber;

SWIFT_CLASS("_TtC8Intercom23HelpCenterMetricService")
@interface HelpCenterMetricService : NSObject
@property (nonatomic) BOOL contextIsSearchBrowse;
+ (void)addSearchBrowseViewedEventWithHomeScreenIndex:(NSInteger)homeScreenIndex;
+ (void)addOpenedFromAPIEvent;
+ (void)addOpenedArticleFromAPIEvent;
+ (void)addOpenedFromConversationEvent;
+ (void)addOpenedFromInAppEvent;
+ (void)addOpenedFromLegacySearchAppEvent;
+ (void)addOpenedFromMessengerHomeAppEvent;
+ (void)addOpenedFromCarousel;
+ (void)addOpenedFromPushNotification;
+ (void)addOpenedFromSurvey;
- (void)addArticleViewedEvent;
- (void)addArticleFailedEventWithErrorCode:(NSNumber * _Nonnull)errorCode;
- (void)addHappyReactionEvent;
- (void)addNeutralReactionEvent;
- (void)addSadReactionEventWithConversationOptionShown:(BOOL)conversationOptionShown;
- (void)addNewConversationFromArticleEventWithAccessToTeammate:(BOOL)accessToTeammate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol HelpCenterStartConversationViewDelegate;

SWIFT_CLASS("_TtC8Intercom31HelpCenterStartConversationView")
@interface HelpCenterStartConversationView : UIView
@property (nonatomic, weak) id <HelpCenterStartConversationViewDelegate> _Nullable startConversationDelegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP8Intercom39HelpCenterStartConversationViewDelegate_")
@protocol HelpCenterStartConversationViewDelegate
- (void)didSelectStartConversation;
@end

@class UIColor;

@interface ICMColor (SWIFT_EXTENSION(Intercom))
+ (BOOL)isLightColor:(UIColor * _Nullable)color SWIFT_WARN_UNUSED_RESULT;
@end

@class NSDate;
@class ICMParticipant;

SWIFT_CLASS("_TtC8Intercom9InboxCell")
@interface InboxCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)configureWithName:(NSString * _Nonnull)name sentTime:(NSDate * _Nonnull)sentTime summary:(NSString * _Nonnull)summary adminsToShow:(NSArray<ICMParticipant *> * _Nonnull)adminsToShow unread:(BOOL)unread showDividerLine:(BOOL)showDividerLine;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
@end


@protocol NativeArticleReactionsViewDelegate;

SWIFT_CLASS("_TtC8Intercom26NativeArticleReactionsView")
@interface NativeArticleReactionsView : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger sadReactionIndex;)
+ (NSInteger)sadReactionIndex SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger neutralReactionIndex;)
+ (NSInteger)neutralReactionIndex SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger happyReactionIndex;)
+ (NSInteger)happyReactionIndex SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <NativeArticleReactionsViewDelegate> _Nullable articleDelegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP8Intercom34NativeArticleReactionsViewDelegate_")
@protocol NativeArticleReactionsViewDelegate
- (void)selectedReactionIndex:(NSInteger)reactionIdex;
@end


SWIFT_CLASS_NAMED("SearchBrowseView")
@interface ICMSearchBrowseView : UIView
- (nonnull instancetype)initWithSuggestedArticles:(NSArray<HelpCenterArticle_Internal *> * _Nonnull)suggestedArticles;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (void)searchHelpArticlesAction;
- (CGFloat)heightForCardWithWidth:(CGFloat)width SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC8Intercom21StartConversationCard")
@interface StartConversationCard : ConversationCard
- (nonnull instancetype)initWithCardInfo:(id <ConversationCardInfoProtocol> _Nonnull)cardInfo delegate:(id <ConversationCardDelegate> _Nonnull)delegate OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP8Intercom10SurveyInfo_")
@protocol SurveyInfo
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@end

enum SurveyFormat : NSInteger;
@class SurveyStep;
@class SurveyCustomizationOptions;

SWIFT_CLASS("_TtC8Intercom6Survey")
@interface Survey : NSObject <SurveyInfo>
@property (nonatomic, readonly, copy, getter=id) NSString * _Nonnull surveyId;
@property (nonatomic, readonly) NSInteger progressId;
@property (nonatomic, readonly, copy) NSString * _Nullable lastStepId;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id format:(enum SurveyFormat)format steps:(NSArray<SurveyStep *> * _Nonnull)steps progressId:(NSInteger)progressId customizationOptions:(SurveyCustomizationOptions * _Nullable)customizationOptions stepCount:(NSInteger)stepCount OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface Survey (SWIFT_EXTENSION(Intercom))
- (NSArray<NSDictionary<NSString *, id> *> * _Nonnull)allResponses SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8Intercom26SurveyCustomizationOptions")
@interface SurveyCustomizationOptions : NSObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull buttonColor;
- (nonnull instancetype)initWithBackgroundColor:(UIColor * _Nonnull)backgroundColor buttonColor:(UIColor * _Nonnull)buttonColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, SurveyFormat, open) {
  SurveyFormatSmall = 0,
  SurveyFormatLarge = 1,
};


SWIFT_CLASS("_TtC8Intercom8SurveyId")
@interface SurveyId : NSObject <SurveyInfo>
@property (nonatomic, copy) NSString * _Nonnull id;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC8Intercom13SurveyService")
@interface SurveyService : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL currentlyDisplayingSurvey;)
+ (BOOL)currentlyDisplayingSurvey SWIFT_WARN_UNUSED_RESULT;
+ (void)setCurrentlyDisplayingSurvey:(BOOL)value;
+ (void)presentSurvey:(Survey * _Nonnull)survey;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8Intercom10SurveyStep")
@interface SurveyStep : NSObject
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@protocol ICMContentViewControllerDelegate;

SWIFT_CLASS("_TtC8Intercom20SurveyViewController")
@interface SurveyViewController : UIViewController
@property (nonatomic, weak) id <ICMContentViewControllerDelegate> _Nullable contentDelegate;
- (nonnull instancetype)initWith:(id <SurveyInfo> _Nonnull)survey OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface SurveyViewController (SWIFT_EXTENSION(Intercom)) <ICMErrorViewDelegate>
- (void)didSelectErrorAction;
@end




@interface SurveyViewController (SWIFT_EXTENSION(Intercom)) <ICMContentViewController>
- (void)reload;
- (void)closeButtonTapped;
- (void)viewDidDismissBySwipe;
@end

@class TicketStatus;
@class ICMFormAttribute;

SWIFT_CLASS("_TtC8Intercom6Ticket")
@interface Ticket : NSObject
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title ticketDescription:(NSString * _Nullable)ticketDescription iconURL:(NSString * _Nullable)iconURL currentStatus:(TicketStatus * _Nonnull)currentStatus statusList:(NSArray<TicketStatus *> * _Nonnull)statusList attributes:(NSArray<ICMFormAttribute *> * _Nonnull)attributes assignee:(ICMParticipant * _Nonnull)assignee OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@protocol IntercomConversationPart;
@protocol IntercomConversationPartDelegate;

SWIFT_CLASS("_TtC8Intercom14TicketCardView")
@interface TicketCardView : IntercomConversationCustomCell
@property (nonatomic, weak) id <CardViewDelegate> _Nullable delegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)configureWithPart:(id <IntercomConversationPart> _Null_unspecified)part reloadDelegate:(id <IntercomConversationPartDelegate> _Null_unspecified)delegate;
+ (CGSize)estimatedSizeForPart:(id <IntercomConversationPart> _Null_unspecified)part withinWidth:(CGFloat)width SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8Intercom27TicketDetailsViewController")
@interface TicketDetailsViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC8Intercom12TicketStatus")
@interface TicketStatus : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title createdDate:(NSDate * _Nullable)createdDate statusDetail:(NSString * _Nullable)statusDetail isCurrentStatus:(BOOL)isCurrentStatus OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class UIEvent;
@class UICollectionViewLayout;

SWIFT_CLASS("_TtC8Intercom30TouchTransparentCollectionView")
@interface TouchTransparentCollectionView : UICollectionView
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame collectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




@interface UIColor (SWIFT_EXTENSION(Intercom))
/// Returns true if the color is white, or almost white.
@property (nonatomic, readonly) BOOL isWhite;
/// Returns true if the color is black, or almost black.
@property (nonatomic, readonly) BOOL isBlack;
@end


@interface UIColor (SWIFT_EXTENSION(Intercom))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nullable intercomGrey;)
+ (UIColor * _Nullable)intercomGrey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nullable intercomBlack;)
+ (UIColor * _Nullable)intercomBlack SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nullable intercomBlack5;)
+ (UIColor * _Nullable)intercomBlack5 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nullable intercomBlack20;)
+ (UIColor * _Nullable)intercomBlack20 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nullable intercomLightGrey;)
+ (UIColor * _Nullable)intercomLightGrey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nullable backButtonBackgroundLight;)
+ (UIColor * _Nullable)backButtonBackgroundLight SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nullable backButtonBackgroundDark;)
+ (UIColor * _Nullable)backButtonBackgroundDark SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nullable coolGray1;)
+ (UIColor * _Nullable)coolGray1 SWIFT_WARN_UNUSED_RESULT;
@end


@interface UIFont (SWIFT_EXTENSION(Intercom))
+ (UIFont * _Nonnull)preferredFontForTextStyle:(UIFontTextStyle _Nonnull)style weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
@end





#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
